apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dolphin-front
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: dolphin-front-instance
          image: clattanoia/dolphin-frontend:latest
          ports:
            - containerPort: 28080
